### ISSUE TITLE
Scaling to larger graphs

### ISSUE THREAD

**Issue by bkj** [snap-stanford/graphwave#2]
The paper states that it scales linearly with the number of edges, and can scale to large sparse graphs -- do you have any examples showing these methods applied to larger graphs?  If not, are there particular practical roadblocks you hit while trying to scale the methods?

Thanks
Ben

**Comment by donnate** [comment]
Hi Ben,

Thank you for your interest in GraphWave!
Yes, the method relies on polynomials on the Laplacian matrix, and as such, scales linearly with the number of edges. I admit not having tried to apply to huge networks yet (but experimentally, it is really fast on graphs up to 1000 nodes, especially compared to some other methods). Some of the methods here in this toolbox have been geared towards visualization and experimentation, and as such, use networkx for plotting. In order to extend this to considerably bigger networks, the best would probably to make a few modifications in order to simply keep a dependency on pygsp (which handles sparse matrices so should be adequate).
Thank you very much for your feedback, and let me know if I can be of any further help!
Best regards,

Claire

**Comment by bkj** [comment]
Thanks for the quick reply.  A few questions:

1) Can you point me to where in the code you're computing the polynomials of the Laplacian matrix?  I'm guessing it's somewhere in the `pygsp` calls, but I'm not very familiar with that library. 

2) In `heat_diffusion.py`, you're looping over each of the nodes in the graph and calling `Hk.analyze` -- so it seems like the complexity should include some function of N as well? 
 Algorithm 1 in the paper does the explicit eigendecomposition, which seems different than the code implementation, so maybe that's where the disconnect is?  (Or maybe I'm misunderstanding the code..)

~ Ben
